import { Viewport } from '@/components/Viewport';
import '@/styles/colors.css';
import '@/styles/globals.css';
import '@/styles/typography.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en">
			<body className={inter.className}>
				<Viewport>{children}</Viewport>
			</body>
		</html>
	);
}
